export const crewMembers = {
  "Camo Choice": [
    {
      id: "camo-1",
      name: "Premium Package",
      description: "Camera + Sound + Lighting crew",
      price: 2500,
      rating: 4.8,
      image: "https://via.placeholder.com/80x80",
      experience: "5+ years",
    },
    {
      id: "camo-2",
      name: "Standard Package",
      description: "Camera + Sound crew",
      price: 1800,
      rating: 4.6,
      image: "https://via.placeholder.com/80x80",
      experience: "3+ years",
    },
  ],
  "Camera crew": [
    {
      id: "cam-1",
      name: "Rajesh Kumar",
      description: "Professional cinematographer",
      price: 1200,
      rating: 4.9,
      image: "https://via.placeholder.com/80x80",
      experience: "7+ years",
    },
    {
      id: "cam-2",
      name: "Amit Singh",
      description: "Wedding & event specialist",
      price: 900,
      rating: 4.7,
      image: "https://via.placeholder.com/80x80",
      experience: "4+ years",
    },
    {
      id: "cam-3",
      name: "Priya Sharma",
      description: "Portrait & fashion photographer",
      price: 1000,
      rating: 4.8,
      image: "https://via.placeholder.com/80x80",
      experience: "5+ years",
    },
  ],
  "Sound Crew": [
    {
      id: "sound-1",
      name: "Vikram Patel",
      description: "Audio engineer & mixer",
      price: 800,
      rating: 4.6,
      image: "https://via.placeholder.com/80x80",
      experience: "6+ years",
    },
    {
      id: "sound-2",
      name: "Neha Agarwal",
      description: "Sound recording specialist",
      price: 650,
      rating: 4.5,
      image: "https://via.placeholder.com/80x80",
      experience: "3+ years",
    },
  ],
};
